## build jdk1.8.60 with centos:youyuan
FROM dockercolin/centos:youyuan
MAINTAINER Colin
ENV JAVA_HOME=/usr/java/jdk1.8.0_40/
RUN yum install -y wget tar
RUN wget --no-cookies \
  --no-check-certificate \
    --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" \
    "http://download.oracle.com/otn-pub/java/jdk/8u40-b26/jdk-8u40-linux-x64.rpm"
RUN rpm -ivh jdk-8u40-linux-x64.rpm && yum clean all
