## build jdk1.7.60 with centos7
FROM dockercolin/centos:youyuan
MAINTAINER Colin 
ENV JAVA_HOME=/usr/java/jdk1.7.0_60/
RUN yum install -y wget tar
RUN wget --no-cookies \
  --no-check-certificate \
  --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" \
  "http://download.oracle.com/otn-pub/java/jdk/7u60-b19/jdk-7u60-linux-x64.rpm"
RUN rpm -ivh jdk-7u60-linux-x64.rpm && yum clean all
